import Phaser from 'phaser';
import type { GameEvents, TowerConfig } from '../../types';
import { TOWER_UPGRADES } from '../../data/towerUpgrades';
import { EventBus } from '../../utils/EventBus';
import { GridManager } from '../../systems/GridManager';
import { PathfindingManager } from '../../systems/PathfindingManager';
import { EconomyManager } from '../../systems/EconomyManager';
import { GridRenderer } from '../../rendering/GridRenderer';
import { BaseTower } from './BaseTower';
import { TowerFactory } from './TowerFactory';
import { BaseEnemy } from '../enemies/BaseEnemy';

export class TowerManager {
  private scene: Phaser.Scene;
  private events: EventBus<GameEvents>;
  private gridManager: GridManager;
  private pathfinding: PathfindingManager;
  private economy: EconomyManager;
  private gridRenderer: GridRenderer;
  private towers: BaseTower[] = [];

  constructor(
    scene: Phaser.Scene,
    events: EventBus<GameEvents>,
    gridManager: GridManager,
    pathfinding: PathfindingManager,
    economy: EconomyManager,
    gridRenderer: GridRenderer,
  ) {
    this.scene = scene;
    this.events = events;
    this.gridManager = gridManager;
    this.pathfinding = pathfinding;
    this.economy = economy;
    this.gridRenderer = gridRenderer;
  }

  placeTower(config: TowerConfig, row: number, col: number): boolean {
    // Check affordability
    if (!this.economy.canAfford(config.baseCost)) {
      this.events.emit('PLACEMENT_REJECTED', { row, col, reason: 'Cannot afford' });
      return false;
    }

    // Check cell is buildable
    if (!this.gridManager.isCellBuildable(row, col)) {
      this.events.emit('PLACEMENT_REJECTED', { row, col, reason: 'Cell occupied' });
      return false;
    }

    // Check path validity
    if (!this.pathfinding.isPathValidWithPlacement(row, col)) {
      this.events.emit('PLACEMENT_REJECTED', { row, col, reason: 'Would block path' });
      return false;
    }

    // Place tower
    const { x, y } = this.gridRenderer.gridToWorld(row, col);
    const tower = TowerFactory.create(this.scene, config, row, col, x, y);

    this.gridManager.placeOnCell(row, col, config.id);
    this.economy.spendGold(config.baseCost);
    this.towers.push(tower);

    // Recalculate path
    this.pathfinding.recalculatePath();

    this.events.emit('TOWER_PLACED', {
      towerId: config.id,
      row,
      col,
      cost: config.baseCost,
    });
    this.events.emit('PATH_UPDATED', {
      waypoints: this.pathfinding.getPath(),
    });

    return true;
  }

  upgradeTower(tower: BaseTower, branchIndex: number): boolean {
    const branches = TOWER_UPGRADES[tower.config.id];
    if (!branches) return false;

    const branch = branches[branchIndex];
    if (!branch) return false;

    const currentBranch = tower.getUpgradeBranch();
    const currentLevel = tower.getUpgradeLevel();

    // If tower already picked a different branch, reject
    if (currentBranch >= 0 && currentBranch !== branchIndex) return false;

    const nextLevel = currentBranch === branchIndex ? currentLevel + 1 : 0;
    const levelData = branch.levels[nextLevel];
    if (!levelData) return false; // already max

    if (!this.economy.spendGold(levelData.cost)) return false;

    tower.applyUpgrade(
      levelData.damageBoost,
      levelData.rangeBoost,
      levelData.speedBoost,
      levelData.cost,
      branchIndex,
      nextLevel,
    );

    this.events.emit('TOWER_UPGRADED', {
      towerId: tower.config.id,
      branch: branchIndex,
      level: nextLevel,
      cost: levelData.cost,
    });

    return true;
  }

  sellTower(tower: BaseTower): void {
    const refund = this.economy.getSellValue(tower.getTotalInvested());
    const row = tower.gridRow;
    const col = tower.gridCol;

    // Remove from tracking
    const index = this.towers.indexOf(tower);
    if (index >= 0) this.towers.splice(index, 1);

    // Free grid cell
    this.gridManager.removeFromCell(row, col);

    // Cleanup tower
    tower.cleanup();

    // Recalculate path
    this.pathfinding.recalculatePath();

    this.events.emit('TOWER_SOLD', {
      towerId: tower.config.id,
      row,
      col,
      refund,
    });
    this.events.emit('PATH_UPDATED', {
      waypoints: this.pathfinding.getPath(),
    });
  }

  update(time: number, delta: number, enemies: BaseEnemy[]): void {
    // Reset buff multipliers each frame (amplifiers will re-apply)
    for (const tower of this.towers) {
      tower.resetBuffMultiplier();
    }

    for (const tower of this.towers) {
      tower.update(time, delta, enemies, this.towers);
      tower.updateProjectiles(time, delta);
    }
  }

  /** Called at wave end: returns total gold generated by Gold Extractors */
  getWaveGoldGeneration(): number {
    let total = 0;
    for (const tower of this.towers) {
      total += tower.getGoldGeneration();
    }
    return total;
  }

  getTowerAt(row: number, col: number): BaseTower | null {
    return this.towers.find(t => t.gridRow === row && t.gridCol === col) ?? null;
  }

  getTowers(): BaseTower[] {
    return this.towers;
  }

  clearAll(): void {
    for (const tower of this.towers) {
      tower.cleanup();
    }
    this.towers = [];
  }
}
